version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont

      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - store_test_results:
          path: jig-core/build/test-results
      - store_test_results:
          path: gradle-plugin/build/test-results

      - store_artifacts:
          path: jig-cli/build/libs
          destination: module

      - run: |
         java -jar jig-cli/build/libs/jig-cli.jar --outputDirectory=example
      - store_artifacts:
          path: example
          destination: example
workflows:
  version: 2
    usually:
      jobs:
        - build:
            filters:
              branches: 'master'
    release:
      jobs:
        - build:
            filters:
              tags:
                only: /.+/

