# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont

      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - store_test_results:
          path: jig-core/build/test-results
      - store_test_results:
          path: gradle-plugin/build/test-results

      - store_artifacts:
          path: class-list-cli/build/libs
          destination: module
      - store_artifacts:
          path: package-diagram-cli/build/libs
          destination: module

      - run: |
         mkdir example
         java -jar class-list-cli/build/libs/class-list-cli.jar --output.list.name=example/class-list.xlsx
         java -jar package-diagram-cli/build/libs/package-diagram-cli.jar --output.diagram.name=example/package-diagram.png
      - store_artifacts:
          path: example
          destination: example

