on:
  push:
    branches:
      - main
jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Gradle
        uses: actions/cache@v2.1.6
        with:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Build
        run: |
          ./gradlew :jig-core:build
      - name: Upload test report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-reports-${{ runner.os }}
          path: jig-core/build/reports/tests/test/
          retention-days: 3
