on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true
        default: '0.0.0-SNAPSHOT'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Gradle
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Build
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_version: ${{ github.event.inputs.version }}
        run: |
          echo "publish as ${{ github.event.inputs.version }}"
          ./gradlew build publishToSonatype
      - name: Upload test failure report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-failure-reports-${{ runner.os }}
          path: jig-*/build/reports/tests/test/
          retention-days: 3
